/**
 * Seeds the local store with one real peak, one real route, and a synthetic
 * but terrain-faithful GPS track.
 *
 * The track is generated by walking the actual Goûter route waypoints on Mont
 * Blanc and sampling the real DEM for elevation, then adding GPS-scale noise.
 * That makes the demo exercise the same code path a genuine upload does —
 * including the height clamp, which only shows its value on real terrain.
 *
 *   npx tsx scripts/seed.ts
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { fetchDemTile } from "../src/lib/geo/fetch-tile";
import { haversine } from "../src/lib/geo/measure";
import { ingestGpx } from "../src/lib/geo/pipeline";
import { sampleElevations } from "../src/lib/geo/terrain";
import { LocalStore } from "../src/lib/store/local";
import type { Peak, Route, Track, Trip, User } from "../src/lib/store/types";
import { TERRAIN_SOURCES } from "../src/lib/tiles/sources";

const DEMO_USER_ID = "00000000-0000-4000-8000-000000000001";
const PEAK_ID = "00000000-0000-4000-8000-000000000010";
const ROUTE_ID = "00000000-0000-4000-8000-000000000020";

/** The classic voie normale, hut by hut. Real coordinates. */
const GOUTER_ROUTE: { name: string; lat: number; lon: number }[] = [
  { name: "Nid d'Aigle", lat: 45.8536, lon: 6.7861 },
  { name: "Baraque des Rognes", lat: 45.8515, lon: 6.8058 },
  { name: "Tête Rousse hut", lat: 45.8489, lon: 6.8206 },
  { name: "Grand Couloir", lat: 45.8497, lon: 6.8253 },
  { name: "Goûter hut", lat: 45.8506, lon: 6.83 },
  { name: "Dôme du Goûter", lat: 45.8419, lon: 6.8497 },
  { name: "Vallot hut", lat: 45.8397, lon: 6.8567 },
  { name: "Bosses ridge", lat: 45.8355, lon: 6.8612 },
  { name: "Summit", lat: 45.8326, lon: 6.8652 },
];

/** Densifies the waypoint polyline to roughly one sample every `spacingM`. */
function densify(
  waypoints: { lat: number; lon: number }[],
  spacingM: number,
): { lat: number; lon: number }[] {
  const out: { lat: number; lon: number }[] = [];

  for (let i = 0; i < waypoints.length - 1; i++) {
    const a = waypoints[i];
    const b = waypoints[i + 1];
    const dist = haversine(a.lat, a.lon, b.lat, b.lon);
    const steps = Math.max(1, Math.round(dist / spacingM));

    for (let s = 0; s < steps; s++) {
      const f = s / steps;
      out.push({ lat: a.lat + (b.lat - a.lat) * f, lon: a.lon + (b.lon - a.lon) * f });
    }
  }
  out.push(waypoints[waypoints.length - 1]);
  return out;
}

/** Deterministic PRNG so re-seeding produces the same demo track. */
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

async function buildGpx(): Promise<string> {
  const spine = densify(GOUTER_ROUTE, 18);
  console.log(`Densified route to ${spine.length} points; sampling DEM…`);

  // z=13 is the finest zoom the AWS terrarium set carries useful detail at for
  // this area; higher just resamples the same underlying elevation model.
  const dem = await sampleElevations(spine, TERRAIN_SOURCES.aws, fetchDemTile, 13);
  const sampled = dem.filter((v) => v !== null).length;
  console.log(`Sampled ${sampled}/${spine.length} points from the DEM.`);

  if (sampled === 0) {
    throw new Error(
      "No DEM samples returned — the terrain tiles are unreachable, so the " +
        "seed track would have no elevation. Check network access and retry.",
    );
  }

  const rand = mulberry32(20250714);
  const start = Date.UTC(2025, 6, 14, 2, 30, 0); // 02:30 alpine start
  let clock = start;

  const rows = spine.map((p, i) => {
    const ground = dem[i];
    // A climber walks on the surface; GPS puts them within a few metres of it.
    const ele = (ground ?? 3000) + 1.5 + (rand() - 0.5) * 6;

    // Pace slows markedly with altitude, which is what makes the moving-time
    // and grade numbers look like a real ascent rather than a constant march.
    const altitudeFactor = 1 + Math.max(0, ((ground ?? 3000) - 2400) / 1200);
    clock += Math.round(14 * altitudeFactor + rand() * 6) * 1000;

    // Horizontal GPS scatter, ~3 m.
    const jitterLat = (rand() - 0.5) * 0.00004;
    const jitterLon = (rand() - 0.5) * 0.00006;

    return {
      lat: p.lat + jitterLat,
      lon: p.lon + jitterLon,
      ele,
      time: new Date(clock).toISOString(),
    };
  });

  const trkpts = rows
    .map(
      (r) =>
        `      <trkpt lat="${r.lat.toFixed(7)}" lon="${r.lon.toFixed(7)}">` +
        `<ele>${r.ele.toFixed(1)}</ele><time>${r.time}</time></trkpt>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="MountainMadness seed" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata><name>Mont Blanc — Goûter route</name></metadata>
  <trk>
    <name>Mont Blanc — Goûter route</name>
    <trkseg>
${trkpts}
    </trkseg>
  </trk>
</gpx>
`;
}

async function main() {
  const gpx = await buildGpx();

  const demoDir = path.join(process.cwd(), "public", "demo");
  await mkdir(demoDir, { recursive: true });
  const gpxPath = path.join(demoDir, "mont-blanc-gouter.gpx");
  await writeFile(gpxPath, gpx, "utf8");
  console.log(`Wrote ${gpxPath}`);

  console.log("Running the ingest pipeline…");
  const result = await ingestGpx(gpx, {
    targetPoints: 3000,
    profileSamples: 500,
    terrain: { source: TERRAIN_SOURCES.aws, fetchTile: fetchDemTile },
  });

  const user: User = {
    id: DEMO_USER_ID,
    handle: "demo",
    displayName: "Demo Climber",
    homeCountry: "FR",
  };

  const peak: Peak = {
    id: PEAK_ID,
    slug: "mont-blanc",
    name: "Mont Blanc",
    lat: 45.8326,
    lon: 6.8652,
    elevationM: 4808,
    prominenceM: 4696,
    countryCode: "FR",
    rangeName: "Graian Alps",
  };

  const route: Route = {
    id: ROUTE_ID,
    peakId: PEAK_ID,
    slug: "gouter",
    name: "Goûter Route",
    discipline: "alpine",
    gradeSystem: "french",
    grade: "PD",
    verticalM: 2436,
    aspectDeg: 315,
    description:
      "The voie normale from the Nid d'Aigle, over the Tête Rousse and Goûter huts, " +
      "across the Dôme du Goûter and up the Bosses ridge to the summit.",
  };

  const trip: Trip = {
    id: "00000000-0000-4000-8000-000000000030",
    userId: DEMO_USER_ID,
    title: "Mont Blanc — Goûter route",
    startedAt: result.startedAt ? new Date(result.startedAt).toISOString() : null,
    peakId: PEAK_ID,
    routeIds: [ROUTE_ID],
    outcome: "summit",
    highpointM: result.stats.maxEleM,
    notes:
      "Left the Goûter at 02:30 with a hard freeze. Bosses ridge in good " +
      "condition, wind picked up above Vallot.",
    // Seeded public so a fresh clone has something to look at; ordinary
    // uploads still default to private.
    visibility: "public",
    createdAt: new Date().toISOString(),
  };

  const track: Track = {
    id: "00000000-0000-4000-8000-000000000040",
    tripId: trip.id,
    source: "gpx",
    rawBlobUrl: "/demo/mont-blanc-gouter.gpx",
    line: result.line,
    bbox: result.bbox,
    stats: result.stats,
    profile: result.profile,
    privacyStartM: result.privacyStartM,
    startedAt: trip.startedAt,
    demSampled: result.demSampled,
  };

  const snapshot = {
    users: [user],
    peaks: [peak],
    routes: [route],
    trips: [trip],
    tracks: [track],
  };

  const store = new LocalStore();
  await store.replaceAll(snapshot);

  // Also write the committed snapshot the app falls back to when no writable
  // data directory exists. This is what makes a fresh deploy show the demo
  // instead of an empty shell: on Vercel the filesystem is read-only, so
  // .data/ never exists there.
  const snapshotPath = path.join(process.cwd(), "src", "lib", "store", "seed-data.json");
  await writeFile(snapshotPath, JSON.stringify(snapshot, null, 2), "utf8");
  console.log(`Wrote ${snapshotPath}`);

  console.log("\nSeeded:");
  console.log(`  peak      Mont Blanc (4808 m)`);
  console.log(`  route     Goûter Route (PD)`);
  console.log(`  track     ${result.line.length} vertices, DEM sampled: ${result.demSampled}`);
  console.log(`  distance  ${(result.stats.distanceM / 1000).toFixed(2)} km`);
  console.log(`  ascent    ${result.stats.gainM} m`);
  console.log(`  descent   ${result.stats.lossM} m`);
  console.log(`  high pt   ${result.stats.maxEleM} m`);
  console.log(`  moving    ${Math.round((result.stats.movingS ?? 0) / 60)} min`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
